version: "3.2"

services:
  social-care-case-viewer-api:
    image: social-care-case-viewer-api
    build:
      context: SocialCareCaseViewerApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - SCCV_MONGO_CONN_STRING=mongodb://mongo-db:27017/?gssapiServiceName=mongodb
      - SCCV_MONGO_DB_NAME=social_care_db_test
      - SCCV_MONGO_COLLECTION_NAME=form_data_test
      - CONNECTION_STRING=Host=test-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
      - SOCIAL_CARE_PLATFORM_API_URL=https://this-is-an-example.com/
    links:
      - mongo-db
      - test-database

  social-care-case-viewer-api-test:
    image: social-care-case-viewer-api-test
    build:
      context: .
      dockerfile: SocialCareCaseViewerApi.Tests/Dockerfile
    environment:
            - MONGO_CONN_STRING=mongodb://mongo-db:27017/?gssapiServiceName=mongodb
            - DB_HOST=test-database
            - DB_USERNAME=postgres
            - DB_PASSWORD=mypassword
            - DB_DATABASE=testdb
            - DB_PORT=5432
    links:
        - mongo-db
        - test-database

  mongo-db:
      image: mongo:3.6
      ports:
        - 1433:27017

  test-database:
    image: test-database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env
